### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by esposm03** [BorisDRYKONINGEN/mininip#1]
I encountered an error that made me unable to use this crate.
The compiler says this
`The package 'mininip' provides no linkable target. The compiler might raise an error while compiling 'xcursor'. Consider adding 'dylib' or 'rlib' to key 'crate-type' in mininip's Cargo.toml.`
Then when I try to `use mininip`, it errors saying that the import cannot be resolved.
I then tried a local copy of the library with `crate-type = "rlib"`, and it worked. I was wondering if this could be pulled into upstream, in order to build using the crates.io version.

**Comment by SlooowAndFurious** [comment]
I modified the crate type to "lib" instead on master and then, merged and reverted it in the FFI branches, which actually need the crate-type to be `staticlib` to be linked with foreign languages such as C. It seems to work fine, I let this issue open for a few days and then, close it

**Comment by esposm03** [comment]
Thanks, it seems to be working for me too! ^^
